Script started on Wed 31 Aug 2016 12:47:47 PM CDT
]0;root@localhost:~/cs161]7;file://localhost.localdomain/root/cs161[?1034h[root@localhost cs161]# cd ~cs[K[K/cs161/root
]0;root@localhost:~/cs161/root]7;file://localhost.localdomain/root/cs161/root[root@localhost root]# ./sys161 kernel
sys161: System/161 release 1.14, compiled Aug 29 2016 19:34:44

OS/161 base system version 1.10
Copyright (c) 2000, 2001, 2002, 2003
   President and Fellows of Harvard College.  All rights reserved.

Put-your-group-name-here's system version 0 (ASST0 #1)

Cpu is MIPS r2000/r3000
1872k physical memory available
Device probe...
lamebus0 (system main bus)
emu0 at lamebus0
ltrace0 at lamebus0
ltimer0 at lamebus0
hardclock on ltimer0 (100 hz)
beep0 at ltimer0
rtclock0 at ltimer0
lrandom0 at lamebus0
random0 at lrandom0
lser0 at lamebus0
con0 at lser0
pseudorand0 (virtual)

OS/161 kernel [? for menu]: p /sbin/poweroff <return>
Operation took 0.000162800 seconds
OS/161 kernel [? for menu]: Shutting down.
The system is halted.
sys161: 263022008 cycles (3986811k, 19u, 259035178i)
sys161: 1698 irqs 6 exns 0r/0w disk 26r/667w console 8r/0w/3m emufs 0r/0w net
sys161: Elapsed real time: 10.520615 seconds (25.0006 mhz)
sys161: Elapsed virtual time: 10.520880320 seconds (25 mhz)
]0;root@localhost:~/cs161/root]7;file://localhost.localdomain/root/cs161/root[root@localhost root]# mv typse[K[Kescript.script ~/cs161/proj/r[Kproj2/run.sc ript
mv: cannot stat ‘typescript.script’: No such file or directory
]0;root@localhost:~/cs161/root]7;file://localhost.localdomain/root/cs161/root[root@localhost root]# exit
exit

Script done on Wed 31 Aug 2016 12:49:04 PM CDT
